import { Metadata } from "next";


export const metadata: Metadata = {
    title: "aBOUT",
    description: "Generated by create next app",
  };



export default function About() {
    return <div>
        <h3>select subitem</h3>
        
    </div>
}