import { Metadata } from "next";


export const metadata: Metadata = {
    title: "contacts",
    description: "Generated by create next app",
  };

export default function Comtacts(){
    return <h1>contact 123-456-789-987-654-321</h1>
}