import { Metadata } from "next";


export const metadata: Metadata = {
    title: "team",
    description: "Generated by create next app",
  };


export default function Team(){
    return <h1>team page Lorem ipsum, dolor sit amet consectetur adipisicing elit. Ratione accusantium rerum voluptas. Exercitationem accusamus perspiciatis magni, quisquam consequatur error dignissimos eos. Adipisci deserunt vero sequi quaerat culpa facere maxime eum.
    Quod cumque dolor nam, similique ea officia dolorem amet porro, ratione animi sapiente fugiat ad dolore facere! Cumque rerum recusandae nemo, perspiciatis quidem voluptatem alias eaque est vel sit itaque?
    </h1>
}